### PR TITLE
AddProduct -- tests, form, view

### PR DESCRIPTION
**Pull request by mdmeyer84**
(one test not passing as this branch currently doesn't have a template for AddProduct)

### CODE REVIEW

**Review by hergotta24 — COMMENTED** [review]
Can you change the branch that your changes are going to get merged into to develop.

**Comment by hergotta24** [comment]
I did go through and review your changes on your branch and everything looks good. I did have 3 tests fail for me, but I believe this is because I changed the model for a product so it's a bit different then what your testing. However that's okay for now we can figure out everything with the models once we know what we want to do on the frontend. I just need you to change the branch from main to develop and I'll approve it.

**Comment by mdmeyer84** [comment]
My bad, changed branch from main to develop

**Review by hergotta24 — APPROVED** [review]
approved

**Pull request merged**
